server:
  shutdown: "graceful"
  compression:
    enabled: true
    min-response-size: 2048

spring:
  application:
    name: Loader
    title: <- loader ->
  output:
    ansi:
      enabled: always
  lifecycle:
    timeout-per-shutdown-phase: "5s"

logging:
  group:
    bluegecko: "uk.co.bluegecko"
  level:
    root: info
    bluegecko: debug

marine:
  back4app:
    enabled: false
    connection:
      scheme: "https"
      host: "parseapi.back4app.com"
      path:
        city: "/classes/Continentscountriescities_City"
    application:
      id: "TGtqdBWPEXhu3nq5eqVSq5JjIIkhLFmcYtsvSAlc"
      key: "00TOggZ8Zqt5mMXu4qr5NhbSCYJR9TR6vajhlUrm"
    limit: 50
  ais:
    enabled: true
    feeds:
      - id: "norway"
        enabled: false
        connection:
          host: "153.44.253.27"
          port: 5631
          protocol: TCP
        tags:
          - SAT
      - id: "test-1"
        connection:
          host: "127.0.0.1"
          port: 10000
          protocol: TCP
        tags:
          - SAT
  loader:
    retry:
      interval: 10
      max: 3